base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('about/', views.about, name = 'about'),
    path('blog/', views.blog, name = 'blog'),
    path('contact/', views.contact, name = 'contact'),
    
    path('shop/', views.shop, name = 'shop'),
    path('shop/product/<pid>/', views.product, name = 'product'),
    path('category/<cid>/', views.categoryProduct, name = 'categoryProduct'),
    path('tag/<slug:tag_slug>/', views.tagList, name = 'tagList'),

    path('vendors/', views.vendors, name = 'vendors'),
    path('vendors/<vid>', views.vendorView, name = 'vendorView'),

    path('compare/', views.compare, name = 'compare'),
    path('checkout/', views.checkout, name = 'checkout'),
    path('wishlist/', views.wishlist, name = 'wishlist'),
    path('cart/', views.cart, name = 'cart'),
    path('order-tracking/', views.orderTracking, name = 'orderTracking'),

    path('user/', include('userauths.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nestEcommerceDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('account/', include('userauths.urls'))
]

base/models.py
from pyexpat import model
from django.db import models
from shortuuidfield import ShortUUIDField
from django.utils.html import mark_safe
from userauths.models import CustomUser
from taggit.managers import TaggableManager

STATUS_CHOICES = (
	("process", "Processing"),
	("shipped", "Shipped"),
	("delivered", "Delivered"),
)

STATUS = (
	("draft", "Draft"),
	("disabled", "Disabled"),
	("rejected", "Rejected"),
	("in_review", "In Review"),
	("published", "Published"),
)

RATING = (
	(1, "⭐"),
	(2, "⭐⭐"),
	(3, "⭐⭐⭐"),
	(4, "⭐⭐⭐⭐"),
	(5, "⭐⭐⭐⭐⭐"),
)

def use_directory_path(instance, filename):
	return 'user_{0}/{1}'.format(instance.user.id, filename)

class Category(models.Model):
	cid = ShortUUIDField(unique=True, max_length=20)

	title = models.CharField(max_length=100, default="John Doe")
	image = models.ImageField(upload_to="category", default="vendor.jpg")

	class Meta:
		verbose_name_plural = "Category"

	def category_image(self):
		return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

	def __str__(self):
		return self.title

class Vendor(models.Model):
	vid = ShortUUIDField(unique=True, max_length=20)

	title = models.CharField(max_length=100, default="John Doe")
	image = models.ImageField(upload_to=use_directory_path, default="vendor.jpg")
	description = models.TextField(null=True, blank=False, default="Vendor description here,.....")

	address = models.CharField(max_length=100, default="123 Kigali Rwanda")
	contact = models.CharField(max_length=100, default="123456789")
	chat_resp_time = models.CharField(max_length=100, default="100")
	shipping_on_time = models.CharField(max_length=100, default="100")
	authentic_rating = models.CharField(max_length=100, default="100")
	days_return = models.CharField(max_length=100, default="100")
	warranty_period = models.CharField(max_length=100, default="100")

	user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
	date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

	class Meta:
		verbose_name_plural = "Vendors"

	def vendor_image(self):
		return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

	def __str__(self):
		return self.title

class Product(models.Model):
	pid = ShortUUIDField(unique=True, max_length=20)

	user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
	category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name="category")
	vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL, null=True, related_name="product")
	
	title = models.CharField(max_length=100, default="Product Title")
	image = models.ImageField(upload_to=use_directory_path, default="product.jpg")
	description = models.TextField(null=True, blank=False, default="This is the Product")

	price = models.DecimalField(max_digits=99999999999, decimal_places=2, default="1.99")
	old_price = models.DecimalField(max_digits=9999999999, decimal_places=2, default="2.99")

	specifications = models.TextField(null=True, blank=True)
	condition = models.CharField(max_length=100, default="Second Hand", null=True, blank=True)
	brand = models.CharField(max_length=100, default="Brand Name", null=True, blank=True)
	model = models.CharField(max_length=100, default="Model Name", null=True, blank=True)

	tags = TaggableManager(blank=True)

	product_status = models.CharField(choices=STATUS, max_length=10, default="in_review")

	status = models.BooleanField(default=True)
	in_stock = models.BooleanField(default=True)
	featured = models.BooleanField(default=True)
	digital = models.BooleanField(default=True)

	sku = ShortUUIDField(unique=True, max_length=10)

	date = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(null=True, blank=True)

	class Meta:
		verbose_name_plural = "Products"

	def product_image(self):
		return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

	def __str__(self):
		return self.title

	def get_percentage(self):
		new_price = (self.price / self.old_price) * 100

		return new_price

class ProductImages(models.Model):
	images = models.ImageField(upload_to="product-images", default="product.jpg")
	product = models.ForeignKey(Product, related_name = "p_images", on_delete=models.SET_NULL, null=True)
	date = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = "Product Images"

class CartOrder(models.Model):
	user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
	price = models.DecimalField(max_digits=99999999999, decimal_places=2, default="1.99")
	paid_status = models.BooleanField(default=False)
	order_date = models.DateTimeField(auto_now_add=True)
	product_status = models.CharField(choices=STATUS_CHOICES, max_length=30, default="processing")

	class Meta:
		verbose_name_plural = "Cart Order"

class CartOrderItems(models.Model):
	order = models.ForeignKey(CartOrder, on_delete=models.CASCADE)
	invoice_no = models.CharField(max_length=200)
	product_status = models.CharField(max_length=200)
	item = models.CharField(max_length=200)
	image = models.CharField(max_length=200)
	qty = models.IntegerField(default=0)
	price = models.DecimalField(max_digits=99999999999, decimal_places=2, default=1.99)
	total = models.DecimalField(max_digits=99999999999, decimal_places=2, default=1.99)

	class Meta:
		verbose_name_plural = "Cart Order Items"

	def order_img(self):
		return mark_safe('<img src="/media/%s" width="50" height="50" />' % (self.image.url))

class ProductReview(models.Model):
	user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
	review = models.TextField()
	rating = models.IntegerField(choices=RATING, default=None)
	date = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = "Product Reviews"

	def __str__(self):
		return self.product.title

	def get_rating(self):
		return self.rating

class Wishlist(models.Model):
	user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
	date = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = "Wishlists"

	def __str__(self):
		return self.product.title

class Address(models.Model):
	user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
	address = models.CharField(max_length=100, null=True)
	status = models.BooleanField(default=False)

	class Meta:
		verbose_name_plural = "Address"

base/views.py
from django.shortcuts import render, get_object_or_404
from base.models import *
from taggit.models import Tag

def home(request):
	categories = Category.objects.all()
	products = Product.objects.all()
	# products = Product.objects.filter(product_status="published", featured=True)

	context = {
		'categories': categories,
		'products': products
	}

	return render(request, 'index.html', context)

def about(request):

	context = {
		
	}

	return render(request, 'about.html', context)

def shop(request):
	categories = Category.objects.all()
	products = Product.objects.order_by("-id")

	context = {
		'categories': categories,
		'products': products
	}

	return render(request, 'shop.html', context)

def product(request, pid):
    product = Product.objects.get(pid=pid)
    products = Product.objects.filter(category=product.category).exclude(pid=pid)[:4]
    p_images = product.p_images.all()

    context = {
        'product': product,
        'products': products,
        'p_images': p_images
    }

    return render(request, 'product.html', context)

def categoryProduct(request, cid):
	category = Category.objects.get(cid=cid)
	products = Product.objects.filter(product_status="published", category=category)

	context = {
		'category': category,
		'products': products
	}

	return render(request, 'categoryProduct.html', context)

def tagList(request, tag_slug=None):
	products = Product.objects.filter(product_status="published").order_by("-id")

	tag = None

	if tag_slug:
		tag = get_object_or_404(Tag, slug=tag_slug)
		products = products.filter(tags__in=[tag])

	context = {
		'products': products,
		'tag': tag
	}

	return render(request, 'tag.html', context)

def vendors(request):
	vendors = Vendor.objects.all()

	context = {
		'vendors': vendors
	}

	return render(request, 'vendors/index.html', context)

def vendorView(request, vid):
	vendor = Vendor.objects.get(vid=vid)
	products = Product.objects.filter(vendor=vendor, product_status="published")

	context = {
		'vendor': vendor,
		'products': products,
	}

	return render(request, 'vendors/detail.html', context)

def blog(request):

	context = {
		
	}

	return render(request, 'blog.html', context)

def contact(request):

	context = {
		
	}

	return render(request, 'contact.html', context)

def compare(request):

	context = {
		
	}

	return render(request, 'compare.html', context)

def checkout(request):

	context = {
		
	}

	return render(request, 'checkout.html', context)

def wishlist(request):

	context = {
		
	}

	return render(request, 'wishlist.html', context)

def cart(request):

	context = {
		
	}

	return render(request, 'cart.html', context)

def orderTracking(request):

	context = {
		
	}

	return render(request, 'orderTracking.html', context)

base/templates/vendors/detail.html
{% extends 'layouts/app.html' %}
{% block title %}Nest Food{% endblock %} 
{% load static %}
{% block content %}

    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="{% url 'base:home' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Store <span></span> Nest Food
            </div>
        </div>
    </div>

    <div class="container mb-30">
        <div class="archive-header-2 text-center pt-80 pb-50">
            <h1 class="display-2 mb-50">Nest Food Store</h1>
            <div class="row">
                <div class="col-lg-5 mx-auto">
                    <div class="sidebar-widget-2 widget_search mb-50">
                        <div class="search-form">
                            <form action="#">
                                <input type="text" placeholder="Search in this store..." />
                                <button type="submit"><i class="fi-rs-search"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row flex-row-reverse">
            <div class="col-lg-4-5">
                <div class="shop-product-fillter">
                    <div class="totall-product">
                        <p>We found <strong class="text-brand">29</strong> items for you!</p>
                    </div>
                    <div class="sort-by-product-area">
                        <div class="sort-by-cover mr-10">
                            <div class="sort-by-product-wrap">
                                <div class="sort-by">
                                    <span><i class="fi-rs-apps"></i>Show:</span>
                                </div>
                                <div class="sort-by-dropdown-wrap">
                                    <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                </div>
                            </div>
                            <div class="sort-by-dropdown">
                                <ul>
                                    <li><a class="active" href="#">50</a></li>
                                    <li><a href="#">100</a></li>
                                    <li><a href="#">150</a></li>
                                    <li><a href="#">200</a></li>
                                    <li><a href="#">All</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="sort-by-cover">
                            <div class="sort-by-product-wrap">
                                <div class="sort-by">
                                    <span><i class="fi-rs-apps-sort"></i>Sort by:</span>
                                </div>
                                <div class="sort-by-dropdown-wrap">
                                    <span> Featured <i class="fi-rs-angle-small-down"></i></span>
                                </div>
                            </div>
                            <div class="sort-by-dropdown">
                                <ul>
                                    <li><a class="active" href="#">Featured</a></li>
                                    <li><a href="#">Price: Low to High</a></li>
                                    <li><a href="#">Price: High to Low</a></li>
                                    <li><a href="#">Release Date</a></li>
                                    <li><a href="#">Avg. Rating</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row product-grid">
                    <div class="col-lg-1-5 col-md-4 col-12 col-sm-6">
                        <div class="product-cart-wrap mb-30">
                            <div class="product-img-action-wrap">
                                <div class="product-img product-img-zoom">
                                    <a href="{% url 'base:product' %}">
                                        <img class="default-img" src="{% static 'assets/imgs/shop/product-1-1.jpg' %}" alt="" />
                                        <img class="hover-img" src="{% static 'assets/imgs/shop/product-1-2.jpg' %}" alt="" />
                                    </a>
                                </div>
                                <div class="product-action-1">
                                    <a aria-label="Add To Wishlist" class="action-btn" href="{% url 'base:wishlist' %}"><i class="fi-rs-heart"></i></a>
                                    <a aria-label="Compare" class="action-btn" href="{% url 'base:compare' %}"><i class="fi-rs-shuffle"></i></a>
                                    <a aria-label="Quick view" class="action-btn" data-bs-toggle="modal" data-bs-target="#quickViewModal"><i class="fi-rs-eye"></i></a>
                                </div>
                                <div class="product-badges product-badges-position product-badges-mrg">
                                    <span class="hot">Hot</span>
                                </div>
                            </div>
                            <div class="product-content-wrap">
                                <div class="product-category">
                                    <a href="{% url 'base:shop' %}">Snack</a>
                                </div>
                                <h2><a href="{% url 'base:product' %}">Seeds of Change Organic Quinoe</a></h2>
                                <div class="product-rate-cover">
                                    <div class="product-rate d-inline-block">
                                        <div class="product-rating" style="width: 90%"></div>
                                    </div>
                                    <span class="font-small ml-5 text-muted"> (4.0)</span>
                                </div>
                                <div>
                                    <span class="font-small text-muted">By <a href="{% url 'base:vendorDetail' %}">NestFood</a></span>
                                </div>
                                <div class="product-card-bottom">
                                    <div class="product-price">
                                        <span>$28.85</span>
                                        <span class="old-price">$32.8</span>
                                    </div>
                                    <div class="add-cart">
                                        <a class="add" href="{% url 'base:cart' %}"><i class="fi-rs-shopping-cart mr-5"></i>Add </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="pagination-area mt-20 mb-20">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-start">
                            <li class="page-item">
                                <a class="page-link" href="#"><i class="fi-rs-arrow-small-left"></i></a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">1</a></li>
                            <li class="page-item active"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                            <li class="page-item"><a class="page-link" href="#">6</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#"><i class="fi-rs-arrow-small-right"></i></a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>

            {% include 'inc/vendor-sidebar.html' %}
        </div>
    </div>

{% endblock content %}

base/templates/vendors/index.html
{% extends 'layouts/app.html' %}
{% block title %}Vendors{% endblock %} 
{% load static %}
{% block content %}

	<div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="{% url 'base:home' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Vendors
            </div>
        </div>
    </div>

    <div class="page-content pt-50">
        <div class="container">
            <div class="archive-header-2 text-center">
                <h1 class="display-2 mb-50">Vendors List</h1>
                <div class="row">
                    <div class="col-lg-5 mx-auto">
                        <div class="sidebar-widget-2 widget_search mb-50">
                            <div class="search-form">
                                <form action="#">
                                    <input type="text" placeholder="Search vendors (by name or ID)..." />
                                    <button type="submit"><i class="fi-rs-search"></i></button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mb-50">
                <div class="col-12 col-lg-8 mx-auto">
                    <div class="shop-product-fillter">
                        <div class="totall-product">
                            <p>We have <strong class="text-brand">780</strong> vendors now</p>
                        </div>
                        <div class="sort-by-product-area">
                            <div class="sort-by-cover mr-10">
                                <div class="sort-by-product-wrap">
                                    <div class="sort-by">
                                        <span><i class="fi-rs-apps"></i>Show:</span>
                                    </div>
                                    <div class="sort-by-dropdown-wrap">
                                        <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                    </div>
                                </div>
                                <div class="sort-by-dropdown">
                                    <ul>
                                        <li><a class="active" href="#">50</a></li>
                                        <li><a href="#">100</a></li>
                                        <li><a href="#">150</a></li>
                                        <li><a href="#">200</a></li>
                                        <li><a href="#">All</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="sort-by-cover">
                                <div class="sort-by-product-wrap">
                                    <div class="sort-by">
                                        <span><i class="fi-rs-apps-sort"></i>Sort by:</span>
                                    </div>
                                    <div class="sort-by-dropdown-wrap">
                                        <span> Featured <i class="fi-rs-angle-small-down"></i></span>
                                    </div>
                                </div>
                                <div class="sort-by-dropdown">
                                    <ul>
                                        <li><a class="active" href="#">Mall</a></li>
                                        <li><a href="#">Featured</a></li>
                                        <li><a href="#">Preferred</a></li>
                                        <li><a href="#">Total items</a></li>
                                        <li><a href="#">Avg. Rating</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row vendor-grid">
                <div class="col-lg-3 col-md-6 col-12 col-sm-6">
                    <div class="vendor-wrap mb-40">
                        <div class="vendor-img-action-wrap">
                            <div class="vendor-img">
                                <a href="{% url 'base:vendorDetail' %}">
                                    <img class="default-img" src="{% static 'assets/imgs/vendor/vendor-1.png' %}" alt="" />
                                </a>
                            </div>
                            <div class="product-badges product-badges-position product-badges-mrg">
                                <span class="hot">Mall</span>
                            </div>
                        </div>
                        <div class="vendor-content-wrap">
                            <div class="d-flex justify-content-between align-items-end mb-30">
                                <div>
                                    <div class="product-category">
                                        <span class="text-muted">Since 2012</span>
                                    </div>
                                    <h4 class="mb-5"><a href="{% url 'base:vendorDetail' %}">Nature Food</a></h4>

                                    <div class="product-rate-cover">
                                        <div class="product-rate d-inline-block">
                                            <div class="product-rating" style="width: 90%"></div>
                                        </div>
                                        <span class="font-small ml-5 text-muted"> (4.0)</span>
                                    </div>
                                </div>

                                <div class="mb-10">
                                    <span class="font-small total-product">380 products</span>
                                </div>
                            </div>

                            <div class="vendor-info mb-30">
                                <ul class="contact-infor text-muted">
                                    <li><img src="{% static 'assets/imgs/theme/icons/icon-location.svg' %}" alt="" /><strong>Address: </strong> <span>5171 W Campbell Ave undefined Kent, Utah 53127 United States</span></li>
                                    <li><img src="{% static 'assets/imgs/theme/icons/icon-contact.svg' %}" alt="" /><strong>Call Us:</strong><span>(+91) - 540-025-124553</span></li>
                                </ul>
                            </div>
                            <a href="{% url 'base:vendorDetail' %}" class="btn btn-xs">Visit Store <i class="fi-rs-arrow-small-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}